export declare const PLAYER_SPEED = 5;
export declare const JUMP_FORCE = 0.15;
export declare const PLAYER_SIZE = 32;
export declare const SPAWN_X = 50;
export declare const SPAWN_Y = 500;
export declare const GROUND_Y = 590;
export declare const FRICTION = 0.001;
export declare const FRICTION_AIR = 0.001;
export declare const RESTITUTION = 0.05;
export declare const PLAYER_MASS = 5;
export declare const GROUND_THRESHOLD = 2;
export declare const MAP_WIDTH = 800;
export declare const MAP_HEIGHT = 600;
export declare const FIXED_TIME_STEP: number;
export declare const GRAVITY_X = 0;
export declare const GRAVITY_Y = 1;
